# Generated by Django 5.0.6 on 2024-05-20 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='onlineliveclass',
            name='class1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
