# Generated by Django 5.0.6 on 2024-05-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceexamquestion',
            name='solution_details',
            field=models.TextField(default='No Solution Available'),
        ),
        migrations.AlterField(
            model_name='liveexamquestion',
            name='solution_details',
            field=models.TextField(default='No Solution Available'),
        ),
    ]
