# Generated by Django 5.0.6 on 2024-05-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice_exam',
            name='duration',
        ),
    ]
