# Generated by Django 5.0.6 on 2024-05-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveexamtimer',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
