# Generated by Django 5.0.6 on 2024-05-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_liveexamtimer_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveexamtimer',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='liveexamtimer',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
