# Generated by Django 5.0.6 on 2024-05-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_subject_teacher_alter_onlineliveclass_class1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineliveclass',
            name='class1',
        ),
    ]
