# Generated by Django 5.0.6 on 2024-05-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_practice_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_exam',
            name='duration',
            field=models.DurationField(default=0),
        ),
    ]
