# Generated by Django 5.0.6 on 2024-05-20 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_onlineliveclass_class1'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineliveclass',
            name='class1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
