# Generated by Django 5.0.6 on 2024-06-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_liveexamquestionoptionselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineliveclass',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
