# Generated by Django 4.2.5 on 2023-09-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_roll_number_customuser_user_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
