# Generated by Django 5.0.6 on 2024-05-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_live_exam_result_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_exam',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
