# Generated by Django 4.2.5 on 2023-09-18 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_fathers_name_customuser_mothers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_class',
        ),
    ]
