# Generated by Django 5.0.6 on 2024-05-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_live_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_exam',
            name='duration',
            field=models.TimeField(default=0),
        ),
    ]
