# Generated by Django 5.0.6 on 2024-06-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_liveexamquestion_liveexammcqquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveExamWrittenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('question', models.CharField(max_length=600)),
                ('solution_details', models.TextField(default='No Solution Available')),
                ('exam', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.live_exam')),
            ],
        ),
        migrations.CreateModel(
            name='LiveExamStudentWrittenAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_image', models.ImageField(upload_to='media/answers/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.liveexamwrittenquestion')),
            ],
        ),
    ]
