# Generated by Django 5.0.6 on 2024-05-21 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Official_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
                ('class_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.class')),
            ],
        ),
    ]
