# Generated by Django 5.0.6 on 2024-06-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_liveexamwrittenquestion_liveexamstudentwrittenanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveexamstudentwrittenanswer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveexamstudentwrittenanswer',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/answers/'),
        ),
    ]
