# Generated by Django 5.0.6 on 2024-05-14 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_live_exam_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live_exam',
            name='is_taken',
        ),
        migrations.RemoveField(
            model_name='live_exam',
            name='user',
        ),
        migrations.CreateModel(
            name='Live_Exam_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.live_exam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
