# Generated by Django 5.0.6 on 2024-05-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentresult_exam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='exam_id',
        ),
    ]
