# Generated by Django 4.2 on 2023-09-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_course_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
