# Generated by Django 5.0.6 on 2024-05-21 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_studentresult_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='exam_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.school_official_exam'),
        ),
    ]
