# Generated by Django 5.0.6 on 2024-05-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_studentresult_exam_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentResult',
            new_name='SchoolExamStudentResult',
        ),
    ]
