# Generated by Django 5.0.6 on 2024-05-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_studentresult_schoolexamstudentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('live_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.live_exam')),
                ('practice_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.practice_exam')),
            ],
        ),
    ]
