# Generated by Django 5.0.6 on 2024-05-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_allexam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllExam',
        ),
    ]
