# Generated by Django 4.2 on 2023-09-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
