# Generated by Django 5.0.6 on 2024-05-22 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_allexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.live_exam_result')),
                ('practice_exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.practice_exam_result')),
            ],
        ),
    ]
