# Generated by Django 5.0.6 on 2024-08-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_live_exam_written_result_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_Notice',
            new_name='Add_Notification',
        ),
        migrations.RenameField(
            model_name='add_notification',
            old_name='notice',
            new_name='notification',
        ),
    ]
