# Generated by Django 5.0.6 on 2024-08-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_notice_created_at_notice_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_Notification',
        ),
    ]
