# Generated by Django 4.2.1 on 2023-09-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('user_class', models.CharField(blank=True, max_length=10, null=True)),
                ('roll', models.PositiveIntegerField()),
                ('mark', models.PositiveIntegerField()),
                ('persentage', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
