# Generated by Django 5.0.6 on 2024-09-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_imagegallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
