# Generated by Django 5.0.6 on 2024-10-26 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_imagegallery_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
