# Generated by Django 5.0.6 on 2024-10-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_studentquestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertextanswer',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
    ]
