# Generated by Django 4.2.1 on 2023-09-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_teacher_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
