# Generated by Django 4.2.1 on 2023-10-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_attendance_attendance_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='subject_id',
        ),
    ]
