# Generated by Django 4.2.1 on 2023-10-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_attendance_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendance_Report',
        ),
    ]
