# Generated by Django 4.2.1 on 2023-10-21 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_attendance_attendance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attendance'),
        ),
    ]
