# Generated by Django 4.2.1 on 2024-03-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
    ]
