# Generated by Django 4.2.1 on 2024-03-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_course_class1_course_created_at_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_class',
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
