# Generated by Django 4.2.1 on 2024-03-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_student_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='course_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.class'),
        ),
    ]
