# Generated by Django 4.2.1 on 2024-03-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_add_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_notice',
            old_name='address',
            new_name='notice',
        ),
    ]
