# Generated by Django 4.2.1 on 2024-03-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_address_add_notice_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
