# Generated by Django 4.2.1 on 2024-03-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_class_class_number_class_next_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='next_class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.class'),
        ),
    ]
