# Generated by Django 4.2.1 on 2024-03-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
