# Generated by Django 4.2.1 on 2024-03-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_exam_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='class_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
