# Generated by Django 4.2.1 on 2024-03-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_exam_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.class'),
        ),
    ]
