# Generated by Django 4.2.1 on 2024-03-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_exam_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='class_id',
            new_name='class1',
        ),
    ]
