# Generated by Django 4.2.1 on 2024-03-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_rename_class_id_exam_class1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='class1',
        ),
    ]
