# Generated by Django 4.2.1 on 2024-03-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_exam_class1'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.class'),
        ),
    ]
