# Generated by Django 4.2.1 on 2024-03-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_exam_class1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='class1',
            new_name='class_id',
        ),
    ]
