# Generated by Django 4.2.1 on 2024-03-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_rename_class1_exam_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='next_class',
        ),
    ]
