# Generated by Django 4.2.1 on 2024-03-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_course_class1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
