# Generated by Django 4.2.1 on 2024-03-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_course_class1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
