# Generated by Django 4.2.1 on 2024-03-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_online_exam_result_exam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam',
            new_name='Practice_Exam',
        ),
    ]
