# Generated by Django 4.2.1 on 2024-05-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_onlineliveclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineLiveClass',
        ),
    ]
