# Generated by Django 4.2.1 on 2024-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_delete_onlineliveclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineLiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('zoom_meeting_id', models.CharField(max_length=255, unique=True)),
                ('start_url', models.URLField()),
                ('join_url', models.URLField()),
                ('password', models.CharField(max_length=255)),
                ('agenda', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
