from django.contrib import admin
from .models import *
from django.contrib.auth.admin import UserAdmin
# Register your models here.
class UserModel(UserAdmin):
    list_display= ['username','user_type','first_name','last_name','mobile_number']
admin.site.register(CustomUser)
admin.site.register(Course)
admin.site.register(Class)
admin.site.register(Session_Year)
admin.site.register(Student)
admin.site.register(Teacher)
admin.site.register(Subject)
admin.site.register(Practice_Exam)
admin.site.register(PracticeExamQuestion)
admin.site.register(Practice_Exam_Result)
admin.site.register(Star_student)
admin.site.register(Teacher_Notification)
admin.site.register(Teacher_Feedback)
admin.site.register(Student_Notification)
admin.site.register(Student_Feedback)
admin.site.register(Attendance)
admin.site.register(Attendance_Report)
admin.site.register(SchoolExamStudentResult)
admin.site.register(Add_Notice)
admin.site.register(OnlineLiveClass)
admin.site.register(Live_Exam)
admin.site.register(LiveExamMCQQuestion)
admin.site.register(Live_Exam_Result)
admin.site.register(Live_Exam_MCQ_Result)
admin.site.register(Live_Exam_Written_Result)
admin.site.register(Live_Exam_MCQ_Report)
admin.site.register(LiveExamQuestionOptionSelect)
admin.site.register(LiveExamTimer)
admin.site.register(Message)
admin.site.register(School_Official_Exam)
admin.site.register(LiveExamWrittenQuestion)
admin.site.register(LiveExamStudentWrittenAnswer)
admin.site.register(Live_Exam_WRITTEN_Report)
